### ISSUE TITLE
Support Soyes XS phone

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-device#152]
logcat output

```
06-03 22:03:51.757 9263-9263/com.geeksville.mesh E/MultiWindowProxy: getServiceInstance failed!
06-03 22:03:52.276 9263-9263/com.geeksville.mesh E/toRemoteExceptions: Uncaught exception, returning to remote client
    com.geeksville.mesh.service.RadioNotConnectedException: We don't yet have our myNodeInfo
        at com.geeksville.mesh.service.MeshService.getMyNodeNum(MeshService.kt:654)
        at com.geeksville.mesh.service.MeshService.getMyNodeID(MeshService.kt:657)
        at com.geeksville.mesh.service.MeshService.access$getMyNodeID$p(MeshService.kt:50)
        at com.geeksville.mesh.service.MeshService$binder$1$getMyId$1.invoke(MeshService.kt:1492)
        at com.geeksville.mesh.service.MeshService$binder$1$getMyId$1.invoke(MeshService.kt:1465)
        at com.geeksville.util.ExceptionsKt.toRemoteExceptions(Exceptions.kt:56)
        at com.geeksville.mesh.service.MeshService$binder$1.getMyId(MeshService.kt:1492)
        at com.geeksville.mesh.MainActivity.updateNodesFromDevice(MainActivity.kt:530)
        at com.geeksville.mesh.MainActivity.access$updateNodesFromDevice(MainActivity.kt:103)
        at com.geeksville.mesh.MainActivity$mesh$1$onConnected$1.invoke(MainActivity.kt:680)
        at com.geeksville.mesh.MainActivity$mesh$1$onConnected$1.invoke(MainActivity.kt:662)
        at com.geeksville.util.ExceptionsKt.exceptionReporter(Exceptions.kt:34)
        at com.geeksville.mesh.MainActivity$mesh$1.onConnected(MainActivity.kt:666)
        at com.geeksville.mesh.MainActivity$mesh$1.onConnected(MainActivity.kt:662)
        at com.geeksville.android.ServiceClient$connection$1$onServiceConnected$1.invoke(ServiceClient.kt:68)
        at com.geeksville.android.ServiceClient$connection$1$onServiceConnected$1.invoke(ServiceClient.kt:63)
        at com.geeksville.util.ExceptionsKt.exceptionReporter(Exceptions.kt:34)
        at com.geeksville.android.ServiceClient$connection$1.onServiceConnected(ServiceClient.kt:64)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1264)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1281)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by geeksville** [comment]
ok - forced logging on for this phone.  Root cause of the problem is that the reconnect BLE interval on this phone is **way** longer than it is supposed to be.
