### ISSUE TITLE
[Bug]: RAK4631 19003 boot loop

### ISSUE THREAD

**Issue by tunip** [meshtastic/Meshtastic-device#1739]
### Category

Other

### Hardware

Rak4631

### Firmware Version

1.3.41.80ddb81

### Description

After flashing 1.3.41 my second RAK4631 is in a boot loop.

My first RAK4631 looks like this:
```
//\ E S H T /\ S T / C

??:??:?? 0 Filesystem files:
??:??:?? 0   RAK (88 Bytes)
??:??:?? 0   MODE (1 Bytes)
??:??:?? 1   db.proto (147 Bytes)
??:??:?? 1   config.proto (90 Bytes)
??:??:?? 1   module.proto (24 Bytes)
??:??:?? 1   channels.proto (53 Bytes)
...
```
But my second one reboots after `RAK (88 Bytes)` message.

Flashing the RAK4631 with an Arduino Example Sketch works fine.

### Relevant log output

```Shell
//\ E S H T /\ S T / C

??:??:?? 1 Filesystem files:
??:??:?? 1   RAK (88 Bytes)
??:??:?? 1    (723605420 Bytes)⸮⸮�@??:??:?? 1 

//\ E S H T /\ S T / C

??:??:?? 1 Filesystem files:
??:??:?? 1   RAK (88 Bytes)
??:??:?? 1    (723605420 Bytes)⸮⸮�@??:??:?? 1 
...

After reflashing bootloader & firmware:
//\ E S H T /\ S T / C

??:??:?? 1 Filesystem files:
??:??:?? 1   RAK (88 Bytes)
??:??:?? 1    (186734508 Bytes)⸮⸮�@??:??:?? 1 

//\ E S H T /\ S T / C

??:??:?? 1 Filesystem files:
??:??:?? 1   RAK (88 Bytes)
??:??:?? 1    (186734508 Bytes)⸮⸮�@??:??:?? 1 
...
```

```
% meshtastic --version
1.3.36
% meshtastic --info
Traceback (most recent call last):
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 621, in write
WARNING file:stream_interface.py __reader line:179 Meshtastic serial port disconnected, disconnecting... read failed: [Errno 6] Device not configured
    n = os.write(self.fd, d)
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joseph/Library/Python/3.9/bin/meshtastic", line 8, in <module>
    sys.exit(main())
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/__main__.py", line 957, in main
    common()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/__main__.py", line 731, in common
    client = meshtastic.serial_interface.SerialInterface(args.port, debugOut=logfile, noProto=args.noproto)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/serial_interface.py", line 57, in __init__
    StreamInterface.__init__(self, debugOut=debugOut, noProto=noProto, connectNow=connectNow)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 50, in __init__
    self.connect()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 71, in connect
    self._startConfig()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/mesh_interface.py", line 456, in _startConfig
    self._sendToRadio(startConfig)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/mesh_interface.py", line 470, in _sendToRadio
    self._sendToRadioImpl(toRadio)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 115, in _sendToRadioImpl
    self._writeBytes(header + b)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 91, in _writeBytes
    self.stream.write(b)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 6] Device not configured
joseph@jDesktop Downloads % meshtastic --info
WARNING file:stream_interface.py __reader line:179 Meshtastic serial port disconnected, disconnecting... read failed: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 621, in write
    n = os.write(self.fd, d)
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joseph/Library/Python/3.9/bin/meshtastic", line 8, in <module>
    sys.exit(main())
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/__main__.py", line 957, in main
    common()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/__main__.py", line 731, in common
    client = meshtastic.serial_interface.SerialInterface(args.port, debugOut=logfile, noProto=args.noproto)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/serial_interface.py", line 57, in __init__
    StreamInterface.__init__(self, debugOut=debugOut, noProto=noProto, connectNow=connectNow)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 50, in __init__
    self.connect()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 71, in connect
    self._startConfig()
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/mesh_interface.py", line 456, in _startConfig
    self._sendToRadio(startConfig)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/mesh_interface.py", line 470, in _sendToRadio
    self._sendToRadioImpl(toRadio)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 115, in _sendToRadioImpl
    self._writeBytes(header + b)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/meshtastic/stream_interface.py", line 91, in _writeBytes
    self.stream.write(b)
  File "/Users/joseph/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 6] Device not configured
```

**Comment by garthvh** [comment]
There is a reset .uf2 file that is pinned to the #nrf52 channel on discord, try dropping that on to the drive and then connecting to it via serial (meshtastic --noproto)  That will wipe all saved data from the device.

**Comment by tunip** [comment]
Many thanks, that helped! Device works again. 👍
