### ISSUE TITLE
[Bug]: Sending commands via the remote channel is broken

### ISSUE THREAD

**Issue by jeremiah-k** [meshtastic/Meshtastic-device#1757]
### Category

Other

### Hardware

T-Beam, Rak4631

### Firmware Version

1.3.41 & pr1715-firmware-1.3.42.dec2785

### Description

My steps to produce the bug:

On the tbeam, I flash to pr1715-firmware-1.3.42.dec2785 via "./device-install.sh -f firmware-tbeam-1.3.42.dec2785.bin" then run:
meshtastic --set lora.region US --seturl https://www.meshtastic.org/e/#Ci0SICYwxfdvjkAmrrnKDxXLVPnOtcTR6y6p-JmjBNg7bRKmGglHcm91cGNoYXQKKRIgQi6cyqQwO2oipZx4psXtOyWZhmWkSFfzcV3Ubtk0N8UaBWFkbWluEggIATgBSAFQHg
(👆  Freshly generated Primary channel + meshtastic --ch-add admin channel)
mehtastic --reboot
(for good measure)
Check settings via
meshtastic --info
Looks good.

On Rak 19007, first flash Meshtastic_nRF52_factory_erase.uf2 via drag & drop method.
Then flash firmware-rak4631-1.3.42.dec2785.uf2 via drag & drop method.
Run the same commands:
meshtastic --set lora.region US --seturl https://www.meshtastic.org/e/#Ci0SICYwxfdvjkAmrrnKDxXLVPnOtcTR6y6p-JmjBNg7bRKmGglHcm91cGNoYXQKKRIgQi6cyqQwO2oipZx4psXtOyWZhmWkSFfzcV3Ubtk0N8UaBWFkbWluEggIATgBSAFQHg
meshtastic --reboot
meshtastic --info
Check settings again, both Primary Channel & admin channel psks match.

Plug in the tbeam again and try:
meshtastic --dest '!22751091' --set-owner "RooftopRak" 

------------

Produces these errors:

Sometimes on the first attempt:

Connected to radio
Setting device owner to RooftopRak
Requesting channel 0 info from remote node (this could take a while)
Requesting channel 1 info from remote node (this could take a while)
Requesting channel 2 info from remote node (this could take a while)
Error: Timed out waiting for node config

------------

On subsequent attempts:

Connected to radio
Setting device owner to RooftopRak
Requesting channel 0 info from remote node (this could take a while)
Requesting channel 1 info from remote node (this could take a while)
ERROR file:stream_interface.py reader line:171 Error while handling message from radio 'admin'
Traceback (most recent call last):
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/stream_interface.py", line 169, in reader
    self._handleFromRadio(self._rxBuf[HEADER_LEN:])
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 537, in _handleFromRadio
    self._handlePacketFromRadio(fromRadio.packet)
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 720, in _handlePacketFromRadio
    handler.callback(asDict)
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/node.py", line 528, in onResponseRequestChannel
    c = p["decoded"]["admin"]["raw"].get_channel_response
KeyError: 'admin' 

(It hangs here until I press Ctrl+C and this is the rest of the error:)

  File "/home/jack/.local/bin/meshtastic", line 8, in <module>
    sys.exit(main())
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/main.py", line 957, in main
    common()
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/main.py", line 742, in common
    onConnected(client)
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/main.py", line 219, in onConnected
    interface.getNode(args.dest).setOwner(args.set_owner)
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 168, in getNode
    if not n.waitForConfig():
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/node.py", line 79, in waitForConfig
    return self._timeout.waitForSet(self, attrs=('localConfig', attribute))
  File "/home/jack/.local/lib/python3.10/site-packages/meshtastic/util.py", line 159, in waitForSet
    time.sleep(self.sleepInterval)
KeyboardInterrupt

**Comment by GUVWAF** [comment]
I think this error is due to that you used a 1.3.41 URL for 1.3.42 devices. I cannot reproduce this with a 1.3.42 URL.  
Regarding the error on your subsequent attempts I opened a [PR](https://github.com/meshtastic/Meshtastic-python/pull/379) to fix this.
